# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
print(arr)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [10]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list2)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [11]:
list3 = [[1,3,5],[7,9,11],[13,15,17]]
arr3 = np.array(list3)
m1 = np.reshape(arr3,(3,3))
print(m1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [24]:
arr4 = np.random.randint(0,10,size=10)
print(arr4)

[9 2 7 7 0 2 3 1 1 5]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [35]:
arr5=np.array([1,2,3,4,5])
arr2d=np.reshape(arr5,(5,-1))
print(arr2d)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


Print the shape of the above created array

In [36]:
print(arr2d.shape)

(5, 1)


Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [44]:
arr6 = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr6[3],arr6[4],arr6[9])

4 5 0


Print alternate elements of that array

In [45]:
for i in range(0,arr6.size,2):
  print(arr6[i])

1
3
5
7
9


Change last 3 elements into 100 using broadcasting and print

In [52]:
 arr6[-3:]=100
 print(arr6)

[  1   2   3   4   5   6   7 100 100 100]


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [50]:
arr7=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20],[21,22,23,24,25]])
m2=np.reshape(arr7,(5,5))
m3=m2[1:4,1:4]
print(m3)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
